#SimuProc 1.4.2.0
LDT ; solicita el primer numero
MOV 1E,AX ;mueve AX a 1E
LDT ; solicita el segundo numero
MOV 2E,AX  ; MUEVE AX A 2E
SUB 1E     ; RESTA A AX EL VALOR DE 1E
JME 00B    ; SI EL FLAG N ES 1 SALTA A 00B
JEQ 00B    ; SI EL FLAG Z ES 1 SALTA A 00B
MOV AX,2E  ;MUEVE 2E A AX
MUL 1E     ; MULTIPLICA AX POR 1E
EAP        ; MUESTRA AX EN PANTALLA
HLT        ; TERMINA EL PROGRAMA
MOV AX,2E  ; MUEVE 2E A AX
ADD 1E     ;SUMA AX MAS 1E
EAP        ;MUESTRA AX EN PANTALLA
HLT         ; TERMINA EL PROGRAMA

